/*
 * This file is generated by AI
 * This file is to be used as a mock dataset for game sessions.
 */

export interface SessionGame {
  name: string;
  minPlayers: number;
  maxPlayers: number;
  enoughPlayers: boolean;
}

export interface Participant {
  name: string;
  game?: string;
}

export interface Session {
  id: number;
  name: string;
  description: string;
  host: string;
  date: string;
  time: string;
  place: string;
  capacity: number;
  confirmed: number;
  status: "Open" | "Full" | "Cancelled";
  waitingList: string[];
  games: SessionGame[];
  participants: Participant[];
}

export const mockSessions: Session[] = [
  {
    id: 1,
    name: "Friday Board Games",
    description: "View information about the session Friday Board Games",
    host: "Alice",
    date: "Friday 18 September",
    time: "19:00",
    place: "Club room",
    capacity: 6,
    confirmed: 4,
    status: "Open",

    waitingList: ["Eve", "Frank"],

    games: [
      {
        name: "Catan",
        minPlayers: 3,
        maxPlayers: 4,
        enoughPlayers: true,
      },
      {
        name: "Carcassonne",
        minPlayers: 2,
        maxPlayers: 5,
        enoughPlayers: true,
      },
    ],

    participants: [
      {
        name: "Alice",
      },
      {
        name: "Bob",
        game: "Catan",
      },
      {
        name: "Charlie",
      },
      {
        name: "David",
        game: "Carcassonne",
      },
    ],
  },

  {
    id: 2,
    name: "Saturday Strategy Night",
    description: "A Saturday evening focused on strategy board games",
    host: "Bob",
    date: "Saturday 19 September",
    time: "18:30",
    place: "Community centre",
    capacity: 8,
    confirmed: 6,
    status: "Open",

    waitingList: ["Grace"],

    games: [
      {
        name: "Terraforming Mars",
        minPlayers: 2,
        maxPlayers: 5,
        enoughPlayers: true,
      },
      {
        name: "Wingspan",
        minPlayers: 1,
        maxPlayers: 5,
        enoughPlayers: true,
      },
      {
        name: "7 Wonders",
        minPlayers: 3,
        maxPlayers: 7,
        enoughPlayers: true,
      },
    ],

    participants: [
      {
        name: "Bob",
        game: "Terraforming Mars",
      },
      {
        name: "Alice",
        game: "Terraforming Mars",
      },
      {
        name: "Charlie",
        game: "Wingspan",
      },
      {
        name: "David",
        game: "Wingspan",
      },
      {
        name: "Eve",
        game: "7 Wonders",
      },
      {
        name: "Frank",
        game: "7 Wonders",
      },
    ],
  },

  {
    id: 3,
    name: "Casual Game Night",
    description: "A relaxed evening with lighter and quicker games",
    host: "Charlie",
    date: "Tuesday 22 September",
    time: "19:30",
    place: "Library meeting room",
    capacity: 6,
    confirmed: 3,
    status: "Open",

    waitingList: [],

    games: [
      {
        name: "Ticket to Ride",
        minPlayers: 2,
        maxPlayers: 5,
        enoughPlayers: true,
      },
      {
        name: "Azul",
        minPlayers: 2,
        maxPlayers: 4,
        enoughPlayers: true,
      },
      {
        name: "Sushi Go!",
        minPlayers: 2,
        maxPlayers: 5,
        enoughPlayers: true,
      },
    ],

    participants: [
      {
        name: "Charlie",
        game: "Ticket to Ride",
      },
      {
        name: "Grace",
        game: "Ticket to Ride",
      },
      {
        name: "Henry",
        game: "Azul",
      },
    ],
  },

  {
    id: 4,
    name: "Sunday Catan Tournament",
    description: "A competitive afternoon of Catan",
    host: "David",
    date: "Sunday 27 September",
    time: "14:00",
    place: "Game café",
    capacity: 12,
    confirmed: 12,
    status: "Full",

    waitingList: ["Alice", "Frank", "Grace"],

    games: [
      {
        name: "Catan",
        minPlayers: 3,
        maxPlayers: 4,
        enoughPlayers: true,
      },
      {
        name: "Catan",
        minPlayers: 3,
        maxPlayers: 4,
        enoughPlayers: true,
      },
      {
        name: "Catan",
        minPlayers: 3,
        maxPlayers: 4,
        enoughPlayers: true,
      },
    ],

    participants: [
      {
        name: "David",
        game: "Catan",
      },
      {
        name: "Bob",
        game: "Catan",
      },
      {
        name: "Charlie",
        game: "Catan",
      },
      {
        name: "Eve",
        game: "Catan",
      },
      {
        name: "Henry",
        game: "Catan",
      },
      {
        name: "Iris",
        game: "Catan",
      },
      {
        name: "Jack",
        game: "Catan",
      },
      {
        name: "Karen",
        game: "Catan",
      },
      {
        name: "Laura",
        game: "Catan",
      },
      {
        name: "Mike",
        game: "Catan",
      },
      {
        name: "Nina",
        game: "Catan",
      },
      {
        name: "Oscar",
        game: "Catan",
      },
    ],
  },

  {
    id: 5,
    name: "Cooperative Games Evening",
    description: "Work together to defeat the game",
    host: "Eve",
    date: "Wednesday 30 September",
    time: "19:00",
    place: "Club room",
    capacity: 5,
    confirmed: 2,
    status: "Open",

    waitingList: [],

    games: [
      {
        name: "Pandemic",
        minPlayers: 2,
        maxPlayers: 4,
        enoughPlayers: true,
      },
      {
        name: "Forbidden Island",
        minPlayers: 2,
        maxPlayers: 4,
        enoughPlayers: true,
      },
    ],

    participants: [
      {
        name: "Eve",
        game: "Pandemic",
      },
      {
        name: "Frank",
        game: "Pandemic",
      },
    ],
  },

  {
    id: 6,
    name: "Carcassonne Beginners Night",
    description: "Learn how to play Carcassonne with other beginners",
    host: "Frank",
    date: "Friday 2 October",
    time: "20:00",
    place: "Community centre",
    capacity: 6,
    confirmed: 5,
    status: "Open",

    waitingList: ["Nina"],

    games: [
      {
        name: "Carcassonne",
        minPlayers: 2,
        maxPlayers: 5,
        enoughPlayers: true,
      },
    ],

    participants: [
      {
        name: "Frank",
        game: "Carcassonne",
      },
      {
        name: "Alice",
        game: "Carcassonne",
      },
      {
        name: "Bob",
        game: "Carcassonne",
      },
      {
        name: "Charlie",
        game: "Carcassonne",
      },
      {
        name: "Grace",
        game: "Carcassonne",
      },
    ],
  },
];
